// Pulls ABIs out of forge artifacts into a typed TS module the app imports.
import { readFileSync, writeFileSync } from "node:fs";

const NAMES = ["CommerceRegistry", "BenefitPass", "VouchCore", "QuestManager", "RewardVault", "MilestoneManager", "Catalog", "PriceOracle", "AppCashback", "MockUSDC"];
const out = ["// GENERATED by scripts/extract-abis.mjs -- do not edit by hand.", ""];

for (const n of NAMES) {
  const artifact = JSON.parse(readFileSync(`contracts/out/${n}.sol/${n}.json`, "utf8"));
  out.push(`export const ${n}Abi = ${JSON.stringify(artifact.abi)} as const;`);
}
writeFileSync("app/lib/abis.ts", out.join("\n") + "\n");
console.log(`wrote app/lib/abis.ts (${NAMES.length} ABIs)`);
